name: Release Artifacts

on:
  push:
    branches:
      - main

jobs:
  build_exe:
    name: Build Windows Exe
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          pip install wheel
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Compile Windows Exe
        run: |
          $version = python setup.py --version
          pyinstaller --onefile -y "FuelHttpHelper.py" -i "FuelHttpHelper.ico" -n "FuelHttpHelper-$version-standalone-win64"
      - name: Upload Windows Exe
        uses: actions/upload-artifact@v3
        with:
          name: artifact-exe
          path: ./dist/*.exe

  release:
    name: Release Artifacts
    runs-on: ubuntu-latest
    needs: [ build_exe ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: Get Version
        run: echo "version=$(python setup.py --version)" >>$GITHUB_OUTPUT
        id: version
      - name: Generate checksum
        run: echo "checksum=$(sha256sum  -b ./artifact-exe/FuelHttpHelper-${{ steps.version.outputs.version }}-standalone-win64.exe)" >>$GITHUB_OUTPUT
        id: checksum
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./artifact-exe/*.exe"
          artifactErrorsFailBuild: true
          body: |
            Please verify the SHA256 checksum before executing:
            
            ${{ steps.checksum.outputs.checksum }}
          tag: v.${{ steps.version.outputs.version }}
          replacesArtifacts: true
